name: lineageOT
channels:
  - defaults
  - bioconda
  - conda-forge
  - etetoolkit
dependencies:
  - anndata>=0.7.4
  - cvxopt>=1.2.0
  - ete3>=3.1.1
  - jupyter>=1.0.0
  - matplotlib>=3.3.4
  - networkx>=2.4
  - python-newick>=1.3.1
  - numpy>=1.19.1
  - pot>=0.7.0


